### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by ronami**
### Summary

Hey, pretty straight-forward: Adding some TypeScript definitions.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for creating a TypeScript definition. 🙌 Can you follow [this styleguide](https://github.com/sindresorhus/typescript-definition-style-guide)?

Some examples:
- https://github.com/sindresorhus/semver-regex/commit/039944bb5b3876913171b895488874b5c200e458
- https://github.com/sindresorhus/global-dirs/commit/0aae4d64887f77af94c4fb7ca12aa9f93c0a8291
- https://github.com/sindresorhus/md5-hex/commit/bbbfeff840f26973fbffc16d4863ae6d120079f3

**Comment by ronami** [comment]
Hey, I updated the PR by documenting the types in `index.d.ts`.

Just pointing out some things in the PR:
- I used `any` over `unknown` to match Node's definition: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.d.ts#L192.
- I used the example from the `README.md` which uses 2 separate files. I wasn't sure how to document it so I used two sets of ```s.

I went over the styleguide and didn't find anything that's missing, is there anything specific I should fix?

Thanks!

**Comment by sindresorhus** [comment]
> I used any over unknown to match Node's definition: DefinitelyTyped/DefinitelyTyped:types/node/globals.d.ts@master#L192 .

The Node.js type definitions are not very good nor strict.

**Comment by sindresorhus** [comment]
Looks good. Thanks :)

**Pull request merged**
